#language: bash
language: python

python:
  - 3.6

cache: pip

sudo: required
  
install:
  - sudo apt install -y lsb-release python3-pip
  - 
  - python3 -m pip install -r requirements.txt

script:
  - python3 Favourite_Packages_Installer.py
