title: iAmLazy
description: This Package allows to install some usefull Applications on a debian based Distro(Ububuntu Obviously).
theme: jekyll-theme-cayman
avatar: https://raw.githubusercontent.com/jekyll/jekyll/master/docs/favicon.ico
show_downloads: true
google_analytics: UA-114697093-1
layout: default
comments: true
messenger: true

# My Custom Configs
ttl:
  seo:
    og-image: https://raw.githubusercontent.com/dreygur/dreygur.github.io/master/img/voldemort.png
